workspace = { members = [ "components/utils","tests"] }
[package]
name = "kisekifs"
version = "0.1.0"
edition = "2021"
authors = ["Ryan Tan"]
license = "Apache-2.0"
description = "A fuse filesystem"
exclude = ["benches"]
autobenches = false

[lib]
bench = false

[[bin]]
name = "kiseki"
path = "src/bin/kiseki.rs"
bench = false

[[bench]]
name = "bench_main"
harness = false
path = "benches/bench_main.rs"

[dependencies]
fuser = { version = "0.14.0", features = ["libfuse","serializable"] }
snafu = "0.8.0"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
serde = "1.0.195"
serde_json = "1.0.111"
features = { version = "0.10.0"}
opendal = { version ="0.44.1", features = ["services-sled"]}
clap = { version = "4.4.16", features = ["derive"]}
libc = "0.2.152"
ctrlc = "3.4.2"
sys-mount = "2.1.1"
const_format = "0.2.32"
procfs = "0.16.0"
lazy_static = "1.4.0"
dashmap = "5.5.3"
byteorder = "1.5.0"
bincode = "1.3.3"
tokio = { version = "1.35.1", features = ["full"]}
log = "0.4.20"
metrics = "0.20.0"
async-channel = "2.1.1"
async-lock = "3.3.0"
hdrhistogram = { version = "7.5.2", default-features = false }
supports-color = "2.1.0"
futures = "0.3.30"
tempfile = "3.9.0"
regex = "1.10.2"
clap-num = "1.0.2"
bitflags = "2.4.2"
scopeguard = "1.2.0"
bytes = "1.5.0"
crossbeam-channel = "0.5.11"
rand = "0.8.5"
tokio-util = { version = "0.7.10", features = ["rt"] }
rustix = "0.38.30"
arrow-buffer = "50.0.0"
datafusion-execution = "35.0.0"
datafusion-common = "35.0.0"
clippy-utilities = "0.2.0"
rangemap = "1.4.0"
num_cpus = "1.16.0"
unique_id = "0.1.5"
sonyflake = "0.2.0"
itertools = "0.12.1"
once_cell = "1.19.0"
bytesize = "1.3.0"
moka = { version = "0.12.5", features = ["future"] }
toml = "0.8.9"
crc32fast = "1.3.2"
async-trait = "0.1.77"

[build-dependencies]
built = {version = "0.7.1", features= ["git2"]}

[dev-dependencies]
criterion = {  version = "0.5.1", features = ["async_tokio","async_futures"] }

