[package]
name = "kisekifs"
version = "0.1.0"
edition = "2021"
authors = ["Ryan Tan"]
license = "Apache-2.0"
description = "A fuse filesystem"

[[bin]]
name = "kiseki"
path = "src/bin/kiseki.rs"

[dependencies]
fuser = { version = "0.14.0", features = ["serializable"]}
snafu = "0.8.0"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
serde = "1.0.195"
serde_json = "1.0.111"
features = { version = "0.10.0"}
opendal = { version ="0.44.1", features = ["services-sled"]}
clap = { version = "4.4.16", features = ["derive"]}
libc = "0.2.152"
ctrlc = "3.4.2"
sys-mount = "2.1.1"
const_format = "0.2.32"
procfs = "0.16.0"
lazy_static = "1.4.0"
dashmap = "5.5.3"
byteorder = "1.5.0"
bincode = "1.3.3"
tokio = { version = "1.35.1", features = ["rt-multi-thread", "macros"]}
log = "0.4.20"
metrics = "0.20.0"
async-channel = "2.1.1"
async-lock = "3.3.0"
hdrhistogram = { version = "7.5.2", default-features = false }
supports-color = "2.1.0"
futures = "0.3.30"
tempfile = "3.9.0"
regex = "1.10.2"
clap-num = "1.0.2"
bitflags = "2.4.2"
scopeguard = "1.2.0"
bytes = "1.5.0"
crossbeam-channel = "0.5.11"
rand = "0.8.5"
tokio-util = "0.7.10"
rustix = "0.38.30"

[build-dependencies]
built = {version = "0.7.1", features= ["git2"]}



