[package]
name = "kisekifs"
version = "0.1.0"
edition = "2021"
description = "A fuse filesystem"

[workspace]
members = ["fs"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
fuser = "0.14.0"
snafu = "0.8.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
[dependencies]



