[package]
name = "kiseki-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snafu.workspace = true
tokio.workspace = true
serde.workspace = true
lazy_static.workspace = true
sonyflake.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true


sentry-tracing = "0.32.2"
dotenvy = "0.15.7"
once_cell = "1.19.0"
supports-color = "3.0.0"
sentry = "0.32.1"
opentelemetry = { version = "0.21.0" }
opentelemetry_sdk = { version = "0.21.0", features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.14.0", default_features=false, features = ["http-proto", "trace", "http", "reqwest-client", "grpc-tonic"] }
opentelemetry-semantic-conventions = "0.13.0"
tracing-opentelemetry = "0.22.0"
tracing-appender = "0.2.3"
proc-macro2 = "1.0.66"
quote = "1.0"
syn = "1.0"
syn2 = { version = "2.0", package = "syn", features = [
    "derive",
    "parsing",
    "printing",
    "clone-impls",
    "proc-macro",
    "extra-traits",
    "full",
] }
