[package]
name = "utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snafu.workspace = true
tokio.workspace = true

# =================================== utils
dotenvy = "0.15.7"

# =================================== Instrumenting
tracing.workspace = true
tracing-subscriber.workspace = true

sentry = "0.32.1"
opentelemetry = { version = "0.21.0" }
opentelemetry_sdk = { version = "0.21.0", features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.14.0", default_features=false, features = ["http-proto", "trace", "http", "reqwest-client"] }
opentelemetry-semantic-conventions = "0.13.0"
tracing-opentelemetry = "0.22.0"
