[package]
name = "storage"
version = "0.1.0"
edition = "2021"
description = "The core storage implementation"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio.workspace = true
tracing.workspace = true
lazy_static.workspace = true
snafu.workspace = true
thingbuf = {version = "0.1.4", features = ["static", "alloc"]}
rand = "0.8.5"


[dev-dependencies]
criterion.workspace = true
kiseki-utils = {path = "../../components/utils"}

[[bench]]
name = "bench_main"
harness = false
path = "benches/bench_main.rs"
