name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]



defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  # Call individual workflow jobs
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml
    secrets: inherit

  rust:
    name: Rust
    uses: ./.github/workflows/rust.yml
    secrets: inherit

  test:
    name: Test
    uses: ./.github/workflows/test.yml
    secrets: inherit
